# Site settings
title: cashow的博客
email: wy89767@163.com
baseurl: "http://cashow.github.io"
author_thumbnail: /assets/images/avatar.png
encoding: utf-8
excerpt_separator: "\n"
url: "" # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#205081" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: cashow

# Build settings
markdown: rdiscount

# Permalinks
permalink: /:title.html

# Pagination config
paginate: 5
paginate_path: "page:num"

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
